apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-connector-cm
data:
  GIT_REPOSITORY_TYPE: {{  .Values.gitRepositoryType}}
  CICD_ORCHESTRATOR_TYPE: {{  .Values.ciCdOrchestratorType}}
  GITOPS_OPERATOR_TYPE: {{  .Values.gitOpsOperatorType}}
  GITOPS_APP_URL: {{  .Values.gitOpsAppURL}}
  
  {{ if eq .Values.gitRepositoryType AZDO}}
  AZDO_GITOPS_REPO_NAME: {{  .Values.azdoGitOpsRepoName}}
  {{ end }}
  
  {{ if eq .Values.ciCdOrchestratorType AZDO}}
  AZDO_PR_REPO_NAME: {{  .Values.azdoPrRepoName}}
  {{ end }}
  
  {{ if or (eq .Values.gitRepositoryType AZDO) (eq .Values.ciCdOrchestratorType AZDO)}}
  AZDO_ORG_URL: {{  .Values.azdoOrgUrl}}
  {{ end }}
  
  
  {{ if eq .Values.ciCdOrchestratorType GITHUB}}
  GITHUB_GITOPS_REPO_NAME: {{  .Values.gitHubGitOpsRepoName}}
  {{ end }}

  {{ if eq .Values.gitRepositoryType GITHUB}}
  GITHUB_GITOPS_MANIFEST_REPO_NAME: {{  .Values.gitHubGitOpsManifestsRepoName}}
  {{ end }}

  {{ if or (eq .Values.gitRepositoryType GITHUB) (eq .Values.ciCdOrchestratorType GITHUB)}}
  GITHUB_ORG_URL: {{  .Values.gitHubOrgUrl}}
  {{ end }}
