name: CD

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: 
      - completed

jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Image Tags
        uses: dawidd6/action-download-artifact@v2
        with:
          name: image_tags
          workflow: ci.yml
          run_id: ${{ github.event.workflow_run.id}}
          path: ${{ github.workspace }}
      - name: Download Manifests
        uses: dawidd6/action-download-artifact@v2
        with:
          name: manifests
          workflow: ci.yml
          run_id: ${{ github.event.workflow_run.id}}
          path: ${{ github.workspace }}
      - name: Read Image Tags
        run: |
          echo "IMAGE_TAG=$(cat ${{ github.workspace }}/IMAGE_TAG)" >> $GITHUB_ENV          
      - name: Read Manifests
        run: |
          ls -ltr ${{ github.workspace }}/manifests
      - name: Generate Manifests
        run: |
          .github/workflows/utils/generate-manifests.sh ${{ github.workspace }}/manifests gen_manifests
        # env:
        #   TARGET_NAMESPACE: ${{ secrets.TARGET_NAMESPACE }}
        #   VOTE_APP_TITLE: ${{ secrets.VOTE_APP_TITLE }}
        #   DEMO_APP_URL: ${{ secrets.DEMO_APP_URL }}
        #   AZURE_VOTE_IMAGE_REPO: ${{ secrets.AZURE_VOTE_IMAGE_REPO }}
      # - name: Create PR
      #   run: |
      #     ${{ github.workspace }}/${{ secrets.UTILS_ARTIFACT_PATH }}/create-pr.sh -s ${{ github.workspace }}/gen_manifests -d ${{ secrets.MANIFESTS_FOLDER }} -r ${{ secrets.MANIFESTS_REPO }} -b ${{ secrets.MANIFESTS_BRANCH }} -i $GITHUB_RUN_ID -t ${{ secrets.PAT }} -e ${{ secrets.ENVIRONMENT_NAME }} -p ${{ secrets.PLATFORM }}


