
name: CI

on:
  push:
    branches:
      - main

jobs:
  code_quality_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: TrueBrain/actions-flake8@master
        name: Linting
        if: "true"
        with:
          path: ./src    
      - uses: hadolint/hadolint-action@v1.5.0
        name: Docker Linting
        with:
          dockerfile: ./src/Dockerfile
      # - name: MD Linting
      #   uses: actionshub/markdownlint@main          

  Build_Push_Image:
    runs-on: ubuntu-latest
    needs: code_quality_checks
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}        
      - name: Generate Image Tag
        run: |
           IMAGE_TAG=${{ secrets.MAJOR_VERSION }}.${{ secrets.MINOR_VERSION }}.${{ github.run_number }}
           echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV          
           echo $IMAGE_TAG > $GITHUB_WORKSPACE/IMAGE_TAG
           cat $GITHUB_WORKSPACE/IMAGE_TAG
      - name: Check Image Tag
        run: |
           echo $IMAGE_TAG
           echo ${{ env.IMAGE_TAG }}           
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ./src
          tags: kaizentm/gitops-connector:${{ env.IMAGE_TAG }}, kaizentm/gitops-connector:latest         


          