
name: CI

on:
  push:
    branches:
      - main

jobs:
  Build_Push_Image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}        
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ./src
          tags: kaizentm/gitops-connector:${{ secrets.MAJOR_VERSION }}.${{ secrets.MINOR_VERSION }}.${{ github.run_number }}, kaizentm/gitops-connector:latest         
          