name: Publish
 
on:
  repository_dispatch:
    types: [sync-success]

jobs:
  update_helm_chart:
    name: "Update Helm Chart"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
